insert into hospital (id, name) values (1, 'Hospital 1');
insert into hospital (id, name) values (2, 'Hospital 2');
insert into hospital (id, name) values (3, 'Hospital 3');
insert into hospital (id, name) values (4, 'Hospital 4');
insert into hospital (id, name) values (5, 'Hospital 5');
insert into department (id, name, organization_id) values (1, 'Department 1', 1);
insert into department (id, name, organization_id) values (2, 'Department 2', 1);
insert into department (id, name, organization_id) values (3, 'Department 3', 1);
insert into department (id, name, organization_id) values (4, 'Department 4', 2);
insert into department (id, name, organization_id) values (5, 'Department 5', 2);
insert into department (id, name, organization_id) values (6, 'Department 6', 3);
insert into department (id, name, organization_id) values (7, 'Department 7', 4);
insert into department (id, name, organization_id) values (8, 'Department 8', 5);
insert into department (id, name, organization_id) values (9, 'Department 9', 5);
insert into employee (id, first_name, last_name, position, salary, age, birthday, department_id, organization_id) values (1, 'John', 'Smith', 'Developer', 10000, 30, '1980-02-02' ,1, 1);
insert into employee (id, first_name, last_name, position, salary, age, birthday, department_id, organization_id) values (2, 'Adam', 'Hamilton', 'Developer', 12000, '1983-03-03',35, 1, 1);
insert into employee (id, first_name, last_name, position, salary, age, birthday, department_id, organization_id) values (3, 'Tracy', 'Smith', 'Architect', 15000, 40, '1985-02-02',1, 1);
insert into employee (id, first_name, last_name, position, salary, age, birthday, department_id, organization_id) values (4, 'Lucy', 'Kim', 'Developer', 13000, 25, 2, '1990-02-01',1);
insert into employee (id, first_name, last_name, position, salary, age, birthday, department_id, organization_id) values (5, 'Peter', 'Wright', 'Director', 50000, 50, '1990-06-02',4, 2);
insert into employee (id, first_name, last_name, position, salary, age, birthday, department_id, organization_id) values (6, 'Alan', 'Murray', 'Developer', 20000, 37, '1990-07-02',4, 2);
insert into employee (id, first_name, last_name, position, salary, age, birthday, department_id, organization_id) values (7, 'Pamela', 'Anderson', 'Analyst', 7000, 27, '1990-08-02',4, 2);